name: geoclic_shared
description: Modèles et utilitaires partagés pour GéoClic V12 Pro
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Géospatial
  latlong2: ^0.9.1

  # Utilitaires
  uuid: ^4.2.1
  intl: any

  # JSON
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
